# Server
server:
  port: 9001
  session:
    timeout: 30
    
# Mybatis
mybatis:
  config-location: classpath:/mybatis/mybatis-postgresql-config.xml
  
# Spring
spring:
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 10MB
      location: /fap
      

# file
file:
  upload:
    location: /fap
    