# Server
server:
  port: 9001
  session:
    timeout: 30
  security:
    user: aqfs
    passowrd: ENC(jXUJALNiX8/ITohBRZFfoUcbvetHC11v)
  ssl:
    enabled: false
    protocol: TLS
    key-store: classpath:nds.ks
    key-store-password: ENC(jXUJALNiX8/ITohBRZFfoUcbvetHC11v)
    key-alias: nds
    key-password: ENC(jXUJALNiX8/ITohBRZFfoUcbvetHC11v)
  redis:
    type: SINGLE
    hosts: 192.168.1.71:6379
    password: ENC(jXUJALNiX8/ITohBRZFfoUcbvetHC11v)
    timeout: 0
    
# Mybatis
mybatis:
  config-location: classpath:/mybatis/mybatis-postgresql-config.xml
  
# Spring
spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: org.postgresql.Driver    
    url: jdbc:postgresql://192.168.1.76:5432/egov2022   
    username: nds
    password: rt12345%   
    dbcp2:
     maxIdle: 10
     test-on-borrow: true
     validation-query: SELECT 1 
  mail:
    host: smtp.gmail.com
    port: 587
    username: rtnetsr@gmail.com
    password: zdsmzojjbvncbyoq
   # username: bowon.lee@rtnet.co.kr
   # password: know3829!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
      
# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# Banner
banner:
  charset: UTF-8
  location: classpath:banner.txt
  